services:
  redis:
    image: redis:7.2-rc-alpine
    container_name: redis
    command: redis-server
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local